import { AppDataSource } from "../../config/database";
import bcrypt from 'bcryptjs';

// User Seeder
export const seedAdminUser = async () => {
    const userRepository = AppDataSource.getRepository('User');
    const cityRepository = AppDataSource.getRepository('PhCity');
    const provinceRepository = AppDataSource.getRepository('PhProvince');
    const regionRepository = AppDataSource.getRepository('PhRegion');

    // Get default location (Manila)
    const ncrRegion = await regionRepository.findOne({ where: { region_code: 'NCR' } });
    const manilaProvince = await provinceRepository.findOne({ where: { province_code: 'NCR' } });
    const manilaCity = await cityRepository.findOne({ where: { name: 'Manila' } });

    const users = [
        {
            email: 'admin@carmarketplace.ph',
            password: 'AdminPass123!',
            first_name: 'System',
            last_name: 'Administrator',
            phone: '+639171234567',
            role: 'admin',
            profile_image: null,
            address: 'Makati City, Metro Manila',
            city_id: manilaCity?.id || 1,
            province_id: manilaProvince?.id || 1,
            region_id: ncrRegion?.id || 1,
            postal_code: '1200',
            barangay: 'Poblacion',
            business_name: 'Car Marketplace Philippines',
            business_permit_number: 'BP-2024-001',
            tin_number: '123-456-789-000',
            dealer_license_number: null,
            email_verified: true,
            phone_verified: true,
            identity_verified: true,
            business_verified: true,
            valid_id_front_url: null,
            valid_id_back_url: null,
            selfie_with_id_url: null,
            business_permit_url: null,
            average_rating: 0.00,
            total_ratings: 0,
            total_sales: 0,
            total_purchases: 0,
            is_active: true,
            is_banned: false,
            ban_reason: null,
            ban_expires_at: null,
            fraud_score: 0.00,
            warning_count: 0,
            last_warning_at: null,
            preferred_currency: 'PHP',
            email_notifications: true,
            sms_notifications: true,
            push_notifications: true,
            last_login_at: new Date(),
            last_login_ip: '127.0.0.1',
            login_count: 1
        },
        {
            email: 'moderator@carmarketplace.ph',
            password: 'ModPass123!',
            first_name: 'Content',
            last_name: 'Moderator',
            phone: '+639181234567',
            role: 'moderator',
            profile_image: null,
            address: 'Quezon City, Metro Manila',
            city_id: manilaCity?.id || 1,
            province_id: manilaProvince?.id || 1,
            region_id: ncrRegion?.id || 1,
            postal_code: '1100',
            barangay: 'Diliman',
            business_name: null,
            business_permit_number: null,
            tin_number: null,
            dealer_license_number: null,
            email_verified: true,
            phone_verified: true,
            identity_verified: true,
            business_verified: false,
            valid_id_front_url: null,
            valid_id_back_url: null,
            selfie_with_id_url: null,
            business_permit_url: null,
            average_rating: 0.00,
            total_ratings: 0,
            total_sales: 0,
            total_purchases: 0,
            is_active: true,
            is_banned: false,
            ban_reason: null,
            ban_expires_at: null,
            fraud_score: 0.00,
            warning_count: 0,
            last_warning_at: null,
            preferred_currency: 'PHP',
            email_notifications: true,
            sms_notifications: true,
            push_notifications: true,
            last_login_at: null,
            last_login_ip: null,
            login_count: 0
        },
        {
            email: 'dealer@carmarketplace.ph',
            password: 'DealerPass123!',
            first_name: 'Honda',
            last_name: 'Dealer',
            phone: '+639191234567',
            role: 'dealer',
            profile_image: null,
            address: 'Pasig City, Metro Manila',
            city_id: manilaCity?.id || 1,
            province_id: manilaProvince?.id || 1,
            region_id: ncrRegion?.id || 1,
            postal_code: '1600',
            barangay: 'Kapitolyo',
            business_name: 'Honda Cars Pasig',
            business_permit_number: 'BP-2024-002',
            tin_number: '987-654-321-000',
            dealer_license_number: 'DL-2024-001',
            email_verified: true,
            phone_verified: true,
            identity_verified: true,
            business_verified: true,
            valid_id_front_url: null,
            valid_id_back_url: null,
            selfie_with_id_url: null,
            business_permit_url: null,
            average_rating: 4.8,
            total_ratings: 125,
            total_sales: 45,
            total_purchases: 0,
            is_active: true,
            is_banned: false,
            ban_reason: null,
            ban_expires_at: null,
            fraud_score: 0.00,
            warning_count: 0,
            last_warning_at: null,
            preferred_currency: 'PHP',
            email_notifications: true,
            sms_notifications: true,
            push_notifications: true,
            last_login_at: null,
            last_login_ip: null,
            login_count: 0
        },
        {
            email: 'seller@carmarketplace.ph',
            password: 'SellerPass123!',
            first_name: 'Juan',
            last_name: 'dela Cruz',
            phone: '+639201234567',
            role: 'seller',
            profile_image: null,
            address: 'Taguig City, Metro Manila',
            city_id: manilaCity?.id || 1,
            province_id: manilaProvince?.id || 1,
            region_id: ncrRegion?.id || 1,
            postal_code: '1630',
            barangay: 'Bonifacio Global City',
            business_name: null,
            business_permit_number: null,
            tin_number: null,
            dealer_license_number: null,
            email_verified: true,
            phone_verified: true,
            identity_verified: true,
            business_verified: false,
            valid_id_front_url: null,
            valid_id_back_url: null,
            selfie_with_id_url: null,
            business_permit_url: null,
            average_rating: 4.5,
            total_ratings: 8,
            total_sales: 3,
            total_purchases: 1,
            is_active: true,
            is_banned: false,
            ban_reason: null,
            ban_expires_at: null,
            fraud_score: 0.00,
            warning_count: 0,
            last_warning_at: null,
            preferred_currency: 'PHP',
            email_notifications: true,
            sms_notifications: false,
            push_notifications: true,
            last_login_at: null,
            last_login_ip: null,
            login_count: 0
        },
        {
            email: 'buyer@carmarketplace.ph',
            password: 'BuyerPass123!',
            first_name: 'Maria',
            last_name: 'Santos',
            phone: '+639211234567',
            role: 'buyer',
            profile_image: null,
            address: 'Mandaluyong City, Metro Manila',
            city_id: manilaCity?.id || 1,
            province_id: manilaProvince?.id || 1,
            region_id: ncrRegion?.id || 1,
            postal_code: '1550',
            barangay: 'Poblacion',
            business_name: null,
            business_permit_number: null,
            tin_number: null,
            dealer_license_number: null,
            email_verified: true,
            phone_verified: false,
            identity_verified: false,
            business_verified: false,
            valid_id_front_url: null,
            valid_id_back_url: null,
            selfie_with_id_url: null,
            business_permit_url: null,
            average_rating: 0.00,
            total_ratings: 0,
            total_sales: 0,
            total_purchases: 0,
            is_active: true,
            is_banned: false,
            ban_reason: null,
            ban_expires_at: null,
            fraud_score: 0.00,
            warning_count: 0,
            last_warning_at: null,
            preferred_currency: 'PHP',
            email_notifications: true,
            sms_notifications: true,
            push_notifications: true,
            last_login_at: null,
            last_login_ip: null,
            login_count: 0
        }
    ];

    for (const userData of users) {
        const existing = await userRepository.findOne({ where: { email: userData.email } });
        if (!existing) {
            // Hash the password
            const passwordHash = await bcrypt.hash(userData.password, 12);
            
            // Remove password from userData and add password_hash
            const { password, ...userWithoutPassword } = userData;
            const userToSave = {
                ...userWithoutPassword,
                password_hash: passwordHash
            };

            await userRepository.save(userToSave);
            console.log(`Created user: ${userData.email} (${userData.role})`);
        } else {
            console.log(`User already exists: ${userData.email}`);
        }
    }

    console.log('Admin and sample users seeded successfully');
};